GET http://localhost:5000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTljMjEzMzhlMzM1NmRiZWQ4NDkxMiIsIm5hbWUiOiJSYWlubiBNb29yZSIsImlhdCI6MTYzNzQ4MjM3N30.5o930STd03EJ5IN_MhymPmG63suFqsk8cnF7PxW-kBE

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "testmail07@abc.com",
    "password": "rainee"
}

###
POST http://localhost:5000/auth/register/
Content-Type: application/json

{
    "firstName": "Rainn",
    "lastName": "Moore",
    "email": "testmail08@abc.com",
    "password": "rainee"
}

###
GET http://localhost:5000/auth/users