GET http://localhost:5000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWE2M2I1NTE2YzFjZGE0N2ZkOTk1NiIsIm5hbWUiOiJYdcOibiBNYWkiLCJpYXQiOjE2Mzc1ODY0MTl9._JbY3Q6kHlu4_7c0mUojgdDRAQz0Y7NjNjIKEgbDNOg

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "testmail07@abc.com",
    "password": "rainee"
}

###
POST http://localhost:5000/auth/register/
Content-Type: application/json

{
    "firstName": "Rainn",
    "lastName": "Moore",
    "email": "testmail08@abc.com",
    "password": "rainee"
}

###
GET http://localhost:5000/auth/users


###
GET http://localhost:5000/6199fb67f6ab37ea8b05f321
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWE2M2I1NTE2YzFjZGE0N2ZkOTk1NiIsIm5hbWUiOiJYdcOibiBNYWkiLCJpYXQiOjE2Mzc1ODY0MTl9._JbY3Q6kHlu4_7c0mUojgdDRAQz0Y7NjNjIKEgbDNOg
